# 1) HTTP -> HTTPS（并统一到 hostname）
server {
    listen 80;
    listen [::]:80;
    server_name itgrep.com www.itgrep.com;

    return 301 https://itgrep.com$request_uri;
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name itgrep.com www.itgrep.com;

    # www -> non-www
    if ($host = "www.itgrep.com") {
        return 301 https://itgrep.com$request_uri;
    }

    ssl_session_cache shared:le_nginx_SSL:1m;
    ssl_session_timeout 1440m;
    ssl_certificate /root/.acme.sh/itgrep.com_ecc/fullchain.cer; # managed by Certbot
    ssl_certificate_key /root/.acme.sh/itgrep.com_ecc/itgrep.com.key; # managed by Certbot
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_prefer_server_ciphers on;

    ssl_ciphers "ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:ECDHE-ECDSA-DES-CBC3-SHA:ECDHE-RSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:DES-CBC3-SHA:!DSS";

    root /root/webapp/nodejs;

    rewrite /(.*)/$ /$1 break ;

    location /robots.txt {
    }

    location = /ads.txt {
       alias /root/webapp/ads.txt/itgrep.com.txt;
    }

    location = /Ads.txt {
       alias /root/webapp/ads.txt/itgrep.com.txt;
    }


    location = / {
        index index.html en.html;        
	sub_filter_once off;
        sub_filter '</body>' '</body><script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-7950559866369342" crossorigin="anonymous"></script>';
	sub_filter  '</head>'  '<script async src="https://www.googletagmanager.com/gtag/js?id=G-6NDMJQNDPS"></script><script>  window.dataLayer = window.dataLayer || [];  function gtag(){dataLayer.push(arguments);}   gtag("js", new Date());  gtag("config", "G-6NDMJQNDPS");</script> </head>';
    }
    
    #location ~ /(.*)/$ {
    #    rewrite /(.*)/$ /$1.html break ; 
    #}


    location / {
	sub_filter_once off;
        sub_filter '</body>' '</body><script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-7950559866369342" crossorigin="anonymous"></script>';
        sub_filter  '</head>'  '<script async src="https://www.googletagmanager.com/gtag/js?id=G-6NDMJQNDPS"></script><script>  window.dataLayer = window.dataLayer || [];  function gtag(){dataLayer.push(arguments);}   gtag("js", new Date());  gtag("config", "G-6NDMJQNDPS");</script> </head>';
        try_files $uri $uri.html;
    }
}

